version: '3'
services:
    mysql-service:
        environment:
            - MYSQL_ROOT_PASSWORD=Devops@123
            - MYSQL_DATABASE=airflowdb
            - MYSQL_USER=devops
            - MYSQL_PASSWORD=Devops@123
        image: mysql:8.0.32
        container_name: airflow_db_containerr
        ports:
            - '3306:3306'
    airflow-service:
        ports:
            - '8081:8080'
        build: .
        container_name: airflow_new_containerrrr

    
